spring.application.name=Spring-Security-Demo-App
spring.datasource.url=jdbc:mysql://localhost:3306/testdb
spring.datasource.username=root
spring.datasource.password=Admin@123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.security.user.name=satya
spring.security.user.password=password

jwt.secret_key = Asdasd657dsASGV876Ajh7VVuty7tytuytutssdas7asda8asd7as79s7as765453sas998dsdadsqw
jwt.access-token-expiration=900000
